# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays:
1. A 1-D array called zeros having 10 elements and all the elements are set to zero.
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19, 99.9, 13
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [45]:
# 1
import numpy as np
zeros=np.zeros(10, dtype=int)
print(zeros)

[0 0 0 0 0 0 0 0 0 0]


In [46]:
# 2
vowels=np.array(['a', 'e', 'o', 'i', 'u'])
print(vowels)

['a' 'e' 'o' 'i' 'u']


In [47]:
# 3
ones= np.array([[1,1,1,1,1],[1,1,1,1,1]])
print(ones)

print("")
# or

one2= np.ones(10, dtype=int).reshape(2,5)
print(one2)

[[1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [48]:
# 4
                       # numpy nested list means np.array
myarray1=np.array([[2.7,  0,  -2],[3.4,  10.6,  0],[-19, 99.9, 13]]) #this is nested

# or

myarray1=np.array([2.7,  0,  -2, 3.4,  10.6,  0,-19, 99.9, 13]).reshape(3,3)
print(myarray1)

[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]


In [49]:
# 5
           #start velue+ total value times step
myarray2=np.arange(4,4+15*4,4, dtype= float).reshape(3,5)
print(myarray2)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following:
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2.
2. Reshape the array ones to have all the 10 elements in a single row.
3. Display the 2nd and 3rd element of the array vowels.
4. Display all elements in the 2nd and 3rd row of the array myarray1.
5. Display the elements in the 1st and 2nd column of the array myarray1.
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
7. Reverse the array of vowels.

In [50]:
# 1
# itemsize how many bytes ... for each element in the arrray takes 8 bytes
print("Zeros: " + str(zeros.shape), zeros.size, zeros.ndim, zeros.dtype, zeros.itemsize)


print("Ones: " + str(ones.shape), ones.size , ones.ndim, ones.dtype, ones.itemsize)

print("myArray1: " + str(myarray1.shape), myarray1.size , myarray1.ndim, myarray1.dtype, myarray1.itemsize)

print("myArra2: " + str(myarray2.shape), myarray2.size , myarray2.ndim, myarray2.dtype, myarray2.itemsize)

Zeros: (10,) 10 1 int64 8
Ones: (2, 5) 10 2 int64 8
myArray1: (3, 3) 9 2 float64 8
myArra2: (3, 5) 15 2 float64 8


In [51]:
# 2
ones=ones.reshape(1,10)
ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [52]:
# 3
vowels[1:3]

array(['e', 'o'], dtype='<U1')

In [53]:
# 4
myarray1[1:3,]#[row:col]
myarray1[1:3,0:2]

array([[  3.4,  10.6],
       [-19. ,  99.9]])

In [54]:
# 5
myarray1[:, 0:2]#all rows, specific cols

array([[  2.7,   0. ],
       [  3.4,  10.6],
       [-19. ,  99.9]])

In [55]:
# 6
myarray1[ 1:3 , 0:1 ]

array([[  3.4],
       [-19. ]])

In [56]:
# 7
vowels[:: -1]
# from the begainning to the end and the step= -1
# or use reverse

# abc=np.array(['a', 'b', 'c', 'd', 'e'])
# abc[:: -1]

array(['u', 'i', 'o', 'e', 'a'], dtype='<U1')

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3.
2. Add the arrays myarray1 and myarray2.
3. Subtract myarray1 from myarray2 and store the result in a new array.
4. Multiply myarray1 and myarray2 elementwise.
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
6. Divide myarray1 by myarray2.
7. Find the cube of all elements of myarray1 and divide the resulting array by 2.
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [57]:
# 1
ones/3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [58]:
# 2
myarray2[:, :3] +myarray1

array([[  6.7,   8. ,  10. ],
       [ 27.4,  38.6,  32. ],
       [ 25. , 147.9,  65. ]])

In [59]:
# 3
sliced_array2 = myarray2[:, :3]
result = myarray1 - sliced_array2
result

array([[ -1.3,  -8. , -14. ],
       [-20.6, -17.4, -32. ],
       [-63. ,  51.9, -39. ]])

In [60]:
# 4
# Slice myarray2 to match the shape of myarray1
sliced_array2 = myarray2[:, :3]

# Perform element-wise multiplication
elementwise_multiplication = myarray1 * sliced_array2
print(elementwise_multiplication)


[[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]


In [61]:
# 5
# Perform matrix multiplication
myarray3 = np.dot(myarray1, myarray2)
print(myarray3)


[[ -77.2  -74.4  -71.6  -68.8  -66. ]
 [ 268.   324.   380.   436.   492. ]
 [2893.6 3269.2 3644.8 4020.4 4396. ]]


In [62]:
# 6
# Perform element-wise division
elementwise_division = myarray1 / sliced_array2
print(elementwise_division)


[[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]


In [63]:
# 7
( myarray1**3 )/2

array([[ 9.841500e+00,  0.000000e+00, -4.000000e+00],
       [ 1.965200e+01,  5.955080e+02,  0.000000e+00],
       [-3.429500e+03,  4.985015e+05,  1.098500e+03]])

In [64]:

# 8
np.round(np.sqrt(myarray2)/2)

array([[1., 1., 2., 2., 2.],
       [2., 3., 3., 3., 3.],
       [3., 3., 4., 4., 4.]])

Using the arrays created above, write NumPy commands for the following:
1. Find the transpose of ones and myarray2.
2. Sort the array vowels in reverse.
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [65]:
# Write your answer here

# 1
print(myarray2.T)
# or
# print(np.transpose(myarray2))

# 2
sorted_vowels = sorted(vowels, reverse=True)
print(sorted_vowels)

# 3
sorted_array = np.sort(myarray1, axis=0)
print(sorted_array)


# np.sort(myarray1)#sort row by row, but col no
# np.sort(myarray1, 1)#sort by row
# np.sort(myarray1, 0)#sort by col




[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
['u', 'o', 'i', 'e', 'a']
[[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

In [66]:
# -1 + step size*num of elements
myarray4 = np.arange(-1, -1 + 0.25*42 , 0.25).reshape(14, 3)
print(myarray4.size)

print("")

print(np.array_split(myarray4,3)) #3 arrays

42

[array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ]]), array([[2.75, 3.  , 3.25],
       [3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75],
       [5.  , 5.25, 5.5 ],
       [5.75, 6.  , 6.25]]), array([[6.5 , 6.75, 7.  ],
       [7.25, 7.5 , 7.75],
       [8.  , 8.25, 8.5 ],
       [8.75, 9.  , 9.25]])]


Using the myarray4 created in the above questions, write commands for the following:
1. Find the sum of all elements.
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise.
4. Find the max of all elements.
5. Find the min of all elements in each row.
6. Find the mean of all elements in each row.
7. Find the standard deviation column wise.

In [67]:
#1
sum = np.sum(myarray4)
print(sum)

# 2
rowise_sum = np.sum(myarray4, axis=1)
rowise_sum

# 3
colwise_sum = np.sum(myarray4, axis=0)
colwise_sum

# 4
colwise_sum = np.sum(myarray4, axis=0)
colwise_sum

# 5
min_row = np.min(myarray4, axis=1)
min_row

# 6
mean_row = np.mean(myarray4, axis=1)
mean_row

# 7
std_col = np.std(myarray4, axis=0)
std_col

173.25


array([3.02334666, 3.02334666, 3.02334666])

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [68]:
import pandas as pd

capitals= pd.read_csv("country-capital-lat-long-population.csv")
capitals.head()

Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770   
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577   
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542   
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526   
4         Andorra       Andorra la Vella   42.5078     1.5211       22614   

  Capital Type  
0      Capital  
1      Capital  
2      Capital  
3      Capital  
4      Capital

In [69]:
import pandas as pd

url = "country-capital-lat-long-population.csv"
df = pd.read_csv(url)  # Corrected to read CSV
df.head()


Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770   
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577   
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542   
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526   
4         Andorra       Andorra la Vella   42.5078     1.5211       22614   

  Capital Type  
0      Capital  
1      Capital  
2      Capital  
3      Capital  
4      Capital

In [70]:
#2 Convert the DataFrame to a NumPy array
numpy_array = df.to_numpy()
numpy_array

array([['Afghanistan', 'Kabul', 34.5289, 69.1725, 4011770, 'Capital'],
       ['Albania', 'Tiranë (Tirana)', 41.3275, 19.8189, 475577,
        'Capital'],
       ['Algeria', 'El Djazaïr  (Algiers)', 36.7525, 3.042, 2693542,
        'Capital'],
       ...,
       ['Yemen', "Sana'a'", 15.3531, 44.2078, 2779317, 'Capital'],
       ['Zambia', 'Lusaka', -15.4134, 28.2771, 2523844, 'Capital'],
       ['Zimbabwe', 'Harare', -17.8294, 31.0539, 1515016, 'Capital']],
      dtype=object)

In [71]:
import pandas as pd
import numpy as np

# Load the data
url = "country-capital-lat-long-population.csv"
df = pd.read_csv(url)

In [72]:
riyadh_coords = df.loc[df['Country'] == 'Saudi Arabia', ['Latitude', 'Longitude']].values[0]

# Remove Riyadh from the dataframe 'no not print it as the closest one to itself'
df_filtered = df[df['Country'] != 'Saudi Arabia']

# Extract the coordinates of all other capitals
other_coords = df_filtered[['Latitude', 'Longitude']].to_numpy()

In [73]:
# Use broadcasting to compute the Euclidean distance from Riyadh to each capital city
distances = np.sqrt((other_coords[:, 0] - riyadh_coords[0])**2 + (other_coords[:, 1] - riyadh_coords[1])**2)

df_filtered['Distance from Riyadh'] = distances

<ipython-input-73-58b6f2288fbb>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Distance from Riyadh'] = distances


In [74]:
# Find the closest capital city
closest_city_idx = np.argmin(distances)
closest_city = df_filtered.iloc[closest_city_idx]['Capital City']  # Get the capital name of the closest city
closest_distance = distances[closest_city_idx]

print(f"The closest capital city to Riyadh is {closest_city} with a distance of {closest_distance:.2f}.")


The closest capital city to Riyadh is Al-Manamah (Manama) with a distance of 4.16.


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [87]:
washington_coords = df.loc[df['Capital City'] == 'Washington, D.C.', ['Latitude', 'Longitude']].values[0]

df_filtered = df[df['Capital City'] != 'Washington, D.C.']

other_coords = df_filtered[['Latitude', 'Longitude']].to_numpy()

distances = np.sqrt((other_coords[:, 0] - washington_coords[0])**2 + (other_coords[:, 1] - washington_coords[1])**2)

df_filtered['Distance from Washington D.C.'] = distances

top_10_closest = df_filtered.nsmallest(10, 'Distance from Washington D.C.')

#top 10 closest capitals
print("The 10 closest capital cities to Washington D.C. are in the following countries:")
print(top_10_closest['Country'].to_list())

#coordinates of the top 10 closest capital cities
top_10_coords = top_10_closest[['Latitude', 'Longitude']].to_numpy()
print("\nCoordinates of the top 10 closest capital cities:")
print(top_10_coords)


The 10 closest capital cities to Washington D.C. are in the following countries:
['Canada', 'Bahamas', 'Bermuda', 'Cuba', 'Turks and Caicos Islands', 'Cayman Islands', 'Haiti', 'Jamaica', 'Dominican Republic', 'Saint Pierre and Miquelon']

Coordinates of the top 10 closest capital cities:
[[ 45.4166 -75.698 ]
 [ 25.0582 -77.3431]
 [ 32.2915 -64.778 ]
 [ 23.1195 -82.3785]
 [ 21.4612 -71.1419]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]
 [ 18.4896 -69.9018]
 [ 46.7738 -56.1815]]


<ipython-input-87-ebb5c4af91b3>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Distance from Washington D.C.'] = distances
